// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_player_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_player_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "item.pb.h"
#include "location.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_player_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_player_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_player_2eproto;
class PBEquipation;
class PBEquipationDefaultTypeInternal;
extern PBEquipationDefaultTypeInternal _PBEquipation_default_instance_;
class PBPlayer;
class PBPlayerDefaultTypeInternal;
extern PBPlayerDefaultTypeInternal _PBPlayer_default_instance_;
class PBSkills;
class PBSkillsDefaultTypeInternal;
extern PBSkillsDefaultTypeInternal _PBSkills_default_instance_;
class PBStats;
class PBStatsDefaultTypeInternal;
extern PBStatsDefaultTypeInternal _PBStats_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PBEquipation* Arena::CreateMaybeMessage<::PBEquipation>(Arena*);
template<> ::PBPlayer* Arena::CreateMaybeMessage<::PBPlayer>(Arena*);
template<> ::PBSkills* Arena::CreateMaybeMessage<::PBSkills>(Arena*);
template<> ::PBStats* Arena::CreateMaybeMessage<::PBStats>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum PBPlayerStats : int {
  HEALTH = 0,
  STRENGTH = 1,
  DEFENSE = 2,
  PRECISION = 3,
  SPEED = 4,
  LUCK = 5,
  PBPlayerStats_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PBPlayerStats_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PBPlayerStats_IsValid(int value);
constexpr PBPlayerStats PBPlayerStats_MIN = HEALTH;
constexpr PBPlayerStats PBPlayerStats_MAX = LUCK;
constexpr int PBPlayerStats_ARRAYSIZE = PBPlayerStats_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PBPlayerStats_descriptor();
template<typename T>
inline const std::string& PBPlayerStats_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PBPlayerStats>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PBPlayerStats_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PBPlayerStats_descriptor(), enum_t_value);
}
inline bool PBPlayerStats_Parse(
    const std::string& name, PBPlayerStats* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PBPlayerStats>(
    PBPlayerStats_descriptor(), name, value);
}
enum PBPlayerSkills : int {
  FORAGE = 0,
  MINING = 1,
  COMBAT = 2,
  ATHLETICS = 3,
  PBPlayerSkills_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PBPlayerSkills_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PBPlayerSkills_IsValid(int value);
constexpr PBPlayerSkills PBPlayerSkills_MIN = FORAGE;
constexpr PBPlayerSkills PBPlayerSkills_MAX = ATHLETICS;
constexpr int PBPlayerSkills_ARRAYSIZE = PBPlayerSkills_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PBPlayerSkills_descriptor();
template<typename T>
inline const std::string& PBPlayerSkills_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PBPlayerSkills>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PBPlayerSkills_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PBPlayerSkills_descriptor(), enum_t_value);
}
inline bool PBPlayerSkills_Parse(
    const std::string& name, PBPlayerSkills* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PBPlayerSkills>(
    PBPlayerSkills_descriptor(), name, value);
}
// ===================================================================

class PBEquipation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBEquipation) */ {
 public:
  inline PBEquipation() : PBEquipation(nullptr) {};
  virtual ~PBEquipation();

  PBEquipation(const PBEquipation& from);
  PBEquipation(PBEquipation&& from) noexcept
    : PBEquipation() {
    *this = ::std::move(from);
  }

  inline PBEquipation& operator=(const PBEquipation& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBEquipation& operator=(PBEquipation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBEquipation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBEquipation* internal_default_instance() {
    return reinterpret_cast<const PBEquipation*>(
               &_PBEquipation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBEquipation& a, PBEquipation& b) {
    a.Swap(&b);
  }
  inline void Swap(PBEquipation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBEquipation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBEquipation* New() const final {
    return CreateMaybeMessage<PBEquipation>(nullptr);
  }

  PBEquipation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBEquipation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBEquipation& from);
  void MergeFrom(const PBEquipation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBEquipation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBEquipation";
  }
  protected:
  explicit PBEquipation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_player_2eproto);
    return ::descriptor_table_player_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttacksFieldNumber = 7,
    kArmorHeadFieldNumber = 1,
    kArmorChestFieldNumber = 2,
    kArmorLeggingsFieldNumber = 3,
    kArmorBootsFieldNumber = 4,
    kWeaponFieldNumber = 5,
    kToolFieldNumber = 6,
  };
  // repeated .PBItemEnum attacks = 7;
  int attacks_size() const;
  private:
  int _internal_attacks_size() const;
  public:
  void clear_attacks();
  private:
  ::PBItemEnum _internal_attacks(int index) const;
  void _internal_add_attacks(::PBItemEnum value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_attacks();
  public:
  ::PBItemEnum attacks(int index) const;
  void set_attacks(int index, ::PBItemEnum value);
  void add_attacks(::PBItemEnum value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& attacks() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_attacks();

  // .PBItemEnum armor_head = 1;
  void clear_armor_head();
  ::PBItemEnum armor_head() const;
  void set_armor_head(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_armor_head() const;
  void _internal_set_armor_head(::PBItemEnum value);
  public:

  // .PBItemEnum armor_chest = 2;
  void clear_armor_chest();
  ::PBItemEnum armor_chest() const;
  void set_armor_chest(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_armor_chest() const;
  void _internal_set_armor_chest(::PBItemEnum value);
  public:

  // .PBItemEnum armor_leggings = 3;
  void clear_armor_leggings();
  ::PBItemEnum armor_leggings() const;
  void set_armor_leggings(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_armor_leggings() const;
  void _internal_set_armor_leggings(::PBItemEnum value);
  public:

  // .PBItemEnum armor_boots = 4;
  void clear_armor_boots();
  ::PBItemEnum armor_boots() const;
  void set_armor_boots(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_armor_boots() const;
  void _internal_set_armor_boots(::PBItemEnum value);
  public:

  // .PBItemEnum weapon = 5;
  void clear_weapon();
  ::PBItemEnum weapon() const;
  void set_weapon(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_weapon() const;
  void _internal_set_weapon(::PBItemEnum value);
  public:

  // .PBItemEnum tool = 6;
  void clear_tool();
  ::PBItemEnum tool() const;
  void set_tool(::PBItemEnum value);
  private:
  ::PBItemEnum _internal_tool() const;
  void _internal_set_tool(::PBItemEnum value);
  public:

  // @@protoc_insertion_point(class_scope:PBEquipation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> attacks_;
  mutable std::atomic<int> _attacks_cached_byte_size_;
  int armor_head_;
  int armor_chest_;
  int armor_leggings_;
  int armor_boots_;
  int weapon_;
  int tool_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_player_2eproto;
};
// -------------------------------------------------------------------

class PBStats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBStats) */ {
 public:
  inline PBStats() : PBStats(nullptr) {};
  virtual ~PBStats();

  PBStats(const PBStats& from);
  PBStats(PBStats&& from) noexcept
    : PBStats() {
    *this = ::std::move(from);
  }

  inline PBStats& operator=(const PBStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBStats& operator=(PBStats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBStats* internal_default_instance() {
    return reinterpret_cast<const PBStats*>(
               &_PBStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PBStats& a, PBStats& b) {
    a.Swap(&b);
  }
  inline void Swap(PBStats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBStats* New() const final {
    return CreateMaybeMessage<PBStats>(nullptr);
  }

  PBStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBStats>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBStats& from);
  void MergeFrom(const PBStats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBStats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBStats";
  }
  protected:
  explicit PBStats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_player_2eproto);
    return ::descriptor_table_player_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxHealthFieldNumber = 1,
    kCurrentHealthFieldNumber = 2,
    kStrengthFieldNumber = 3,
    kDefenseFieldNumber = 4,
    kPrecisionFieldNumber = 5,
    kSpeedFieldNumber = 6,
    kLuckFieldNumber = 7,
  };
  // int32 max_health = 1;
  void clear_max_health();
  ::PROTOBUF_NAMESPACE_ID::int32 max_health() const;
  void set_max_health(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_health() const;
  void _internal_set_max_health(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 current_health = 2;
  void clear_current_health();
  ::PROTOBUF_NAMESPACE_ID::int32 current_health() const;
  void set_current_health(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_current_health() const;
  void _internal_set_current_health(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 strength = 3;
  void clear_strength();
  ::PROTOBUF_NAMESPACE_ID::int32 strength() const;
  void set_strength(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_strength() const;
  void _internal_set_strength(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 defense = 4;
  void clear_defense();
  ::PROTOBUF_NAMESPACE_ID::int32 defense() const;
  void set_defense(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_defense() const;
  void _internal_set_defense(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 precision = 5;
  void clear_precision();
  ::PROTOBUF_NAMESPACE_ID::int32 precision() const;
  void set_precision(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_precision() const;
  void _internal_set_precision(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 speed = 6;
  void clear_speed();
  ::PROTOBUF_NAMESPACE_ID::int32 speed() const;
  void set_speed(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_speed() const;
  void _internal_set_speed(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 luck = 7;
  void clear_luck();
  ::PROTOBUF_NAMESPACE_ID::int32 luck() const;
  void set_luck(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_luck() const;
  void _internal_set_luck(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:PBStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_health_;
  ::PROTOBUF_NAMESPACE_ID::int32 current_health_;
  ::PROTOBUF_NAMESPACE_ID::int32 strength_;
  ::PROTOBUF_NAMESPACE_ID::int32 defense_;
  ::PROTOBUF_NAMESPACE_ID::int32 precision_;
  ::PROTOBUF_NAMESPACE_ID::int32 speed_;
  ::PROTOBUF_NAMESPACE_ID::int32 luck_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_player_2eproto;
};
// -------------------------------------------------------------------

class PBSkills PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBSkills) */ {
 public:
  inline PBSkills() : PBSkills(nullptr) {};
  virtual ~PBSkills();

  PBSkills(const PBSkills& from);
  PBSkills(PBSkills&& from) noexcept
    : PBSkills() {
    *this = ::std::move(from);
  }

  inline PBSkills& operator=(const PBSkills& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBSkills& operator=(PBSkills&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBSkills& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBSkills* internal_default_instance() {
    return reinterpret_cast<const PBSkills*>(
               &_PBSkills_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PBSkills& a, PBSkills& b) {
    a.Swap(&b);
  }
  inline void Swap(PBSkills* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBSkills* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBSkills* New() const final {
    return CreateMaybeMessage<PBSkills>(nullptr);
  }

  PBSkills* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBSkills>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBSkills& from);
  void MergeFrom(const PBSkills& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBSkills* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBSkills";
  }
  protected:
  explicit PBSkills(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_player_2eproto);
    return ::descriptor_table_player_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kForagingXpFieldNumber = 2,
    kForagingLvlFieldNumber = 1,
    kMiningLvlFieldNumber = 3,
    kMiningXpFieldNumber = 4,
    kCombatXpFieldNumber = 6,
    kCombatLvlFieldNumber = 5,
    kAthleticsLvlFieldNumber = 7,
    kAthleticsXpFieldNumber = 8,
  };
  // int64 foraging_xp = 2;
  void clear_foraging_xp();
  ::PROTOBUF_NAMESPACE_ID::int64 foraging_xp() const;
  void set_foraging_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_foraging_xp() const;
  void _internal_set_foraging_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 foraging_lvl = 1;
  void clear_foraging_lvl();
  ::PROTOBUF_NAMESPACE_ID::int32 foraging_lvl() const;
  void set_foraging_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_foraging_lvl() const;
  void _internal_set_foraging_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 mining_lvl = 3;
  void clear_mining_lvl();
  ::PROTOBUF_NAMESPACE_ID::int32 mining_lvl() const;
  void set_mining_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_mining_lvl() const;
  void _internal_set_mining_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 mining_xp = 4;
  void clear_mining_xp();
  ::PROTOBUF_NAMESPACE_ID::int64 mining_xp() const;
  void set_mining_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_mining_xp() const;
  void _internal_set_mining_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 combat_xp = 6;
  void clear_combat_xp();
  ::PROTOBUF_NAMESPACE_ID::int64 combat_xp() const;
  void set_combat_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_combat_xp() const;
  void _internal_set_combat_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 combat_lvl = 5;
  void clear_combat_lvl();
  ::PROTOBUF_NAMESPACE_ID::int32 combat_lvl() const;
  void set_combat_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_combat_lvl() const;
  void _internal_set_combat_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 athletics_lvl = 7;
  void clear_athletics_lvl();
  ::PROTOBUF_NAMESPACE_ID::int32 athletics_lvl() const;
  void set_athletics_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_athletics_lvl() const;
  void _internal_set_athletics_lvl(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 athletics_xp = 8;
  void clear_athletics_xp();
  ::PROTOBUF_NAMESPACE_ID::int64 athletics_xp() const;
  void set_athletics_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_athletics_xp() const;
  void _internal_set_athletics_xp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:PBSkills)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 foraging_xp_;
  ::PROTOBUF_NAMESPACE_ID::int32 foraging_lvl_;
  ::PROTOBUF_NAMESPACE_ID::int32 mining_lvl_;
  ::PROTOBUF_NAMESPACE_ID::int64 mining_xp_;
  ::PROTOBUF_NAMESPACE_ID::int64 combat_xp_;
  ::PROTOBUF_NAMESPACE_ID::int32 combat_lvl_;
  ::PROTOBUF_NAMESPACE_ID::int32 athletics_lvl_;
  ::PROTOBUF_NAMESPACE_ID::int64 athletics_xp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_player_2eproto;
};
// -------------------------------------------------------------------

class PBPlayer PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBPlayer) */ {
 public:
  inline PBPlayer() : PBPlayer(nullptr) {};
  virtual ~PBPlayer();

  PBPlayer(const PBPlayer& from);
  PBPlayer(PBPlayer&& from) noexcept
    : PBPlayer() {
    *this = ::std::move(from);
  }

  inline PBPlayer& operator=(const PBPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBPlayer& operator=(PBPlayer&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBPlayer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBPlayer* internal_default_instance() {
    return reinterpret_cast<const PBPlayer*>(
               &_PBPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PBPlayer& a, PBPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(PBPlayer* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBPlayer* New() const final {
    return CreateMaybeMessage<PBPlayer>(nullptr);
  }

  PBPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBPlayer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBPlayer& from);
  void MergeFrom(const PBPlayer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBPlayer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBPlayer";
  }
  protected:
  explicit PBPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_player_2eproto);
    return ::descriptor_table_player_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 3,
    kLastOnlineFieldNumber = 4,
    kStatsFieldNumber = 8,
    kSkillsFieldNumber = 9,
    kEquipationFieldNumber = 10,
    kDiscordIdFieldNumber = 1,
    kPlayerIdFieldNumber = 2,
    kCurrentLocationFieldNumber = 7,
    kGuildIdFieldNumber = 6,
  };
  // string user_name = 3;
  void clear_user_name();
  const std::string& user_name() const;
  void set_user_name(const std::string& value);
  void set_user_name(std::string&& value);
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  std::string* mutable_user_name();
  std::string* release_user_name();
  void set_allocated_user_name(std::string* user_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_user_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_user_name(
      std::string* user_name);
  private:
  const std::string& _internal_user_name() const;
  void _internal_set_user_name(const std::string& value);
  std::string* _internal_mutable_user_name();
  public:

  // .google.protobuf.Timestamp last_online = 4;
  bool has_last_online() const;
  private:
  bool _internal_has_last_online() const;
  public:
  void clear_last_online();
  const PROTOBUF_NAMESPACE_ID::Timestamp& last_online() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_last_online();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_last_online();
  void set_allocated_last_online(PROTOBUF_NAMESPACE_ID::Timestamp* last_online);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_last_online() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_last_online();
  public:
  void unsafe_arena_set_allocated_last_online(
      PROTOBUF_NAMESPACE_ID::Timestamp* last_online);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_last_online();

  // .PBStats stats = 8;
  bool has_stats() const;
  private:
  bool _internal_has_stats() const;
  public:
  void clear_stats();
  const ::PBStats& stats() const;
  ::PBStats* release_stats();
  ::PBStats* mutable_stats();
  void set_allocated_stats(::PBStats* stats);
  private:
  const ::PBStats& _internal_stats() const;
  ::PBStats* _internal_mutable_stats();
  public:
  void unsafe_arena_set_allocated_stats(
      ::PBStats* stats);
  ::PBStats* unsafe_arena_release_stats();

  // .PBSkills skills = 9;
  bool has_skills() const;
  private:
  bool _internal_has_skills() const;
  public:
  void clear_skills();
  const ::PBSkills& skills() const;
  ::PBSkills* release_skills();
  ::PBSkills* mutable_skills();
  void set_allocated_skills(::PBSkills* skills);
  private:
  const ::PBSkills& _internal_skills() const;
  ::PBSkills* _internal_mutable_skills();
  public:
  void unsafe_arena_set_allocated_skills(
      ::PBSkills* skills);
  ::PBSkills* unsafe_arena_release_skills();

  // .PBEquipation equipation = 10;
  bool has_equipation() const;
  private:
  bool _internal_has_equipation() const;
  public:
  void clear_equipation();
  const ::PBEquipation& equipation() const;
  ::PBEquipation* release_equipation();
  ::PBEquipation* mutable_equipation();
  void set_allocated_equipation(::PBEquipation* equipation);
  private:
  const ::PBEquipation& _internal_equipation() const;
  ::PBEquipation* _internal_mutable_equipation();
  public:
  void unsafe_arena_set_allocated_equipation(
      ::PBEquipation* equipation);
  ::PBEquipation* unsafe_arena_release_equipation();

  // uint64 discord_id = 1;
  void clear_discord_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 discord_id() const;
  void set_discord_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_discord_id() const;
  void _internal_set_discord_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 player_id = 2;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::int32 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .PBLocationID current_location = 7;
  void clear_current_location();
  ::PBLocationID current_location() const;
  void set_current_location(::PBLocationID value);
  private:
  ::PBLocationID _internal_current_location() const;
  void _internal_set_current_location(::PBLocationID value);
  public:

  // uint64 guild_id = 6;
  void clear_guild_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 guild_id() const;
  void set_guild_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_guild_id() const;
  void _internal_set_guild_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:PBPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_name_;
  PROTOBUF_NAMESPACE_ID::Timestamp* last_online_;
  ::PBStats* stats_;
  ::PBSkills* skills_;
  ::PBEquipation* equipation_;
  ::PROTOBUF_NAMESPACE_ID::uint64 discord_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 player_id_;
  int current_location_;
  ::PROTOBUF_NAMESPACE_ID::uint64 guild_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_player_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBEquipation

// .PBItemEnum armor_head = 1;
inline void PBEquipation::clear_armor_head() {
  armor_head_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_armor_head() const {
  return static_cast< ::PBItemEnum >(armor_head_);
}
inline ::PBItemEnum PBEquipation::armor_head() const {
  // @@protoc_insertion_point(field_get:PBEquipation.armor_head)
  return _internal_armor_head();
}
inline void PBEquipation::_internal_set_armor_head(::PBItemEnum value) {
  
  armor_head_ = value;
}
inline void PBEquipation::set_armor_head(::PBItemEnum value) {
  _internal_set_armor_head(value);
  // @@protoc_insertion_point(field_set:PBEquipation.armor_head)
}

// .PBItemEnum armor_chest = 2;
inline void PBEquipation::clear_armor_chest() {
  armor_chest_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_armor_chest() const {
  return static_cast< ::PBItemEnum >(armor_chest_);
}
inline ::PBItemEnum PBEquipation::armor_chest() const {
  // @@protoc_insertion_point(field_get:PBEquipation.armor_chest)
  return _internal_armor_chest();
}
inline void PBEquipation::_internal_set_armor_chest(::PBItemEnum value) {
  
  armor_chest_ = value;
}
inline void PBEquipation::set_armor_chest(::PBItemEnum value) {
  _internal_set_armor_chest(value);
  // @@protoc_insertion_point(field_set:PBEquipation.armor_chest)
}

// .PBItemEnum armor_leggings = 3;
inline void PBEquipation::clear_armor_leggings() {
  armor_leggings_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_armor_leggings() const {
  return static_cast< ::PBItemEnum >(armor_leggings_);
}
inline ::PBItemEnum PBEquipation::armor_leggings() const {
  // @@protoc_insertion_point(field_get:PBEquipation.armor_leggings)
  return _internal_armor_leggings();
}
inline void PBEquipation::_internal_set_armor_leggings(::PBItemEnum value) {
  
  armor_leggings_ = value;
}
inline void PBEquipation::set_armor_leggings(::PBItemEnum value) {
  _internal_set_armor_leggings(value);
  // @@protoc_insertion_point(field_set:PBEquipation.armor_leggings)
}

// .PBItemEnum armor_boots = 4;
inline void PBEquipation::clear_armor_boots() {
  armor_boots_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_armor_boots() const {
  return static_cast< ::PBItemEnum >(armor_boots_);
}
inline ::PBItemEnum PBEquipation::armor_boots() const {
  // @@protoc_insertion_point(field_get:PBEquipation.armor_boots)
  return _internal_armor_boots();
}
inline void PBEquipation::_internal_set_armor_boots(::PBItemEnum value) {
  
  armor_boots_ = value;
}
inline void PBEquipation::set_armor_boots(::PBItemEnum value) {
  _internal_set_armor_boots(value);
  // @@protoc_insertion_point(field_set:PBEquipation.armor_boots)
}

// .PBItemEnum weapon = 5;
inline void PBEquipation::clear_weapon() {
  weapon_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_weapon() const {
  return static_cast< ::PBItemEnum >(weapon_);
}
inline ::PBItemEnum PBEquipation::weapon() const {
  // @@protoc_insertion_point(field_get:PBEquipation.weapon)
  return _internal_weapon();
}
inline void PBEquipation::_internal_set_weapon(::PBItemEnum value) {
  
  weapon_ = value;
}
inline void PBEquipation::set_weapon(::PBItemEnum value) {
  _internal_set_weapon(value);
  // @@protoc_insertion_point(field_set:PBEquipation.weapon)
}

// .PBItemEnum tool = 6;
inline void PBEquipation::clear_tool() {
  tool_ = 0;
}
inline ::PBItemEnum PBEquipation::_internal_tool() const {
  return static_cast< ::PBItemEnum >(tool_);
}
inline ::PBItemEnum PBEquipation::tool() const {
  // @@protoc_insertion_point(field_get:PBEquipation.tool)
  return _internal_tool();
}
inline void PBEquipation::_internal_set_tool(::PBItemEnum value) {
  
  tool_ = value;
}
inline void PBEquipation::set_tool(::PBItemEnum value) {
  _internal_set_tool(value);
  // @@protoc_insertion_point(field_set:PBEquipation.tool)
}

// repeated .PBItemEnum attacks = 7;
inline int PBEquipation::_internal_attacks_size() const {
  return attacks_.size();
}
inline int PBEquipation::attacks_size() const {
  return _internal_attacks_size();
}
inline void PBEquipation::clear_attacks() {
  attacks_.Clear();
}
inline ::PBItemEnum PBEquipation::_internal_attacks(int index) const {
  return static_cast< ::PBItemEnum >(attacks_.Get(index));
}
inline ::PBItemEnum PBEquipation::attacks(int index) const {
  // @@protoc_insertion_point(field_get:PBEquipation.attacks)
  return _internal_attacks(index);
}
inline void PBEquipation::set_attacks(int index, ::PBItemEnum value) {
  attacks_.Set(index, value);
  // @@protoc_insertion_point(field_set:PBEquipation.attacks)
}
inline void PBEquipation::_internal_add_attacks(::PBItemEnum value) {
  attacks_.Add(value);
}
inline void PBEquipation::add_attacks(::PBItemEnum value) {
  // @@protoc_insertion_point(field_add:PBEquipation.attacks)
  _internal_add_attacks(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
PBEquipation::attacks() const {
  // @@protoc_insertion_point(field_list:PBEquipation.attacks)
  return attacks_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
PBEquipation::_internal_mutable_attacks() {
  return &attacks_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
PBEquipation::mutable_attacks() {
  // @@protoc_insertion_point(field_mutable_list:PBEquipation.attacks)
  return _internal_mutable_attacks();
}

// -------------------------------------------------------------------

// PBStats

// int32 max_health = 1;
inline void PBStats::clear_max_health() {
  max_health_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_max_health() const {
  return max_health_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::max_health() const {
  // @@protoc_insertion_point(field_get:PBStats.max_health)
  return _internal_max_health();
}
inline void PBStats::_internal_set_max_health(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  max_health_ = value;
}
inline void PBStats::set_max_health(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_health(value);
  // @@protoc_insertion_point(field_set:PBStats.max_health)
}

// int32 current_health = 2;
inline void PBStats::clear_current_health() {
  current_health_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_current_health() const {
  return current_health_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::current_health() const {
  // @@protoc_insertion_point(field_get:PBStats.current_health)
  return _internal_current_health();
}
inline void PBStats::_internal_set_current_health(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  current_health_ = value;
}
inline void PBStats::set_current_health(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_current_health(value);
  // @@protoc_insertion_point(field_set:PBStats.current_health)
}

// int32 strength = 3;
inline void PBStats::clear_strength() {
  strength_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_strength() const {
  return strength_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::strength() const {
  // @@protoc_insertion_point(field_get:PBStats.strength)
  return _internal_strength();
}
inline void PBStats::_internal_set_strength(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  strength_ = value;
}
inline void PBStats::set_strength(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_strength(value);
  // @@protoc_insertion_point(field_set:PBStats.strength)
}

// int32 defense = 4;
inline void PBStats::clear_defense() {
  defense_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_defense() const {
  return defense_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::defense() const {
  // @@protoc_insertion_point(field_get:PBStats.defense)
  return _internal_defense();
}
inline void PBStats::_internal_set_defense(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  defense_ = value;
}
inline void PBStats::set_defense(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_defense(value);
  // @@protoc_insertion_point(field_set:PBStats.defense)
}

// int32 precision = 5;
inline void PBStats::clear_precision() {
  precision_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_precision() const {
  return precision_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::precision() const {
  // @@protoc_insertion_point(field_get:PBStats.precision)
  return _internal_precision();
}
inline void PBStats::_internal_set_precision(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  precision_ = value;
}
inline void PBStats::set_precision(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_precision(value);
  // @@protoc_insertion_point(field_set:PBStats.precision)
}

// int32 speed = 6;
inline void PBStats::clear_speed() {
  speed_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_speed() const {
  return speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::speed() const {
  // @@protoc_insertion_point(field_get:PBStats.speed)
  return _internal_speed();
}
inline void PBStats::_internal_set_speed(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  speed_ = value;
}
inline void PBStats::set_speed(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:PBStats.speed)
}

// int32 luck = 7;
inline void PBStats::clear_luck() {
  luck_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::_internal_luck() const {
  return luck_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBStats::luck() const {
  // @@protoc_insertion_point(field_get:PBStats.luck)
  return _internal_luck();
}
inline void PBStats::_internal_set_luck(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  luck_ = value;
}
inline void PBStats::set_luck(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_luck(value);
  // @@protoc_insertion_point(field_set:PBStats.luck)
}

// -------------------------------------------------------------------

// PBSkills

// int32 foraging_lvl = 1;
inline void PBSkills::clear_foraging_lvl() {
  foraging_lvl_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::_internal_foraging_lvl() const {
  return foraging_lvl_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::foraging_lvl() const {
  // @@protoc_insertion_point(field_get:PBSkills.foraging_lvl)
  return _internal_foraging_lvl();
}
inline void PBSkills::_internal_set_foraging_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  foraging_lvl_ = value;
}
inline void PBSkills::set_foraging_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_foraging_lvl(value);
  // @@protoc_insertion_point(field_set:PBSkills.foraging_lvl)
}

// int64 foraging_xp = 2;
inline void PBSkills::clear_foraging_xp() {
  foraging_xp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::_internal_foraging_xp() const {
  return foraging_xp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::foraging_xp() const {
  // @@protoc_insertion_point(field_get:PBSkills.foraging_xp)
  return _internal_foraging_xp();
}
inline void PBSkills::_internal_set_foraging_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  foraging_xp_ = value;
}
inline void PBSkills::set_foraging_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_foraging_xp(value);
  // @@protoc_insertion_point(field_set:PBSkills.foraging_xp)
}

// int32 mining_lvl = 3;
inline void PBSkills::clear_mining_lvl() {
  mining_lvl_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::_internal_mining_lvl() const {
  return mining_lvl_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::mining_lvl() const {
  // @@protoc_insertion_point(field_get:PBSkills.mining_lvl)
  return _internal_mining_lvl();
}
inline void PBSkills::_internal_set_mining_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mining_lvl_ = value;
}
inline void PBSkills::set_mining_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_mining_lvl(value);
  // @@protoc_insertion_point(field_set:PBSkills.mining_lvl)
}

// int64 mining_xp = 4;
inline void PBSkills::clear_mining_xp() {
  mining_xp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::_internal_mining_xp() const {
  return mining_xp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::mining_xp() const {
  // @@protoc_insertion_point(field_get:PBSkills.mining_xp)
  return _internal_mining_xp();
}
inline void PBSkills::_internal_set_mining_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  mining_xp_ = value;
}
inline void PBSkills::set_mining_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_mining_xp(value);
  // @@protoc_insertion_point(field_set:PBSkills.mining_xp)
}

// int32 combat_lvl = 5;
inline void PBSkills::clear_combat_lvl() {
  combat_lvl_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::_internal_combat_lvl() const {
  return combat_lvl_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::combat_lvl() const {
  // @@protoc_insertion_point(field_get:PBSkills.combat_lvl)
  return _internal_combat_lvl();
}
inline void PBSkills::_internal_set_combat_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  combat_lvl_ = value;
}
inline void PBSkills::set_combat_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_combat_lvl(value);
  // @@protoc_insertion_point(field_set:PBSkills.combat_lvl)
}

// int64 combat_xp = 6;
inline void PBSkills::clear_combat_xp() {
  combat_xp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::_internal_combat_xp() const {
  return combat_xp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::combat_xp() const {
  // @@protoc_insertion_point(field_get:PBSkills.combat_xp)
  return _internal_combat_xp();
}
inline void PBSkills::_internal_set_combat_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  combat_xp_ = value;
}
inline void PBSkills::set_combat_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_combat_xp(value);
  // @@protoc_insertion_point(field_set:PBSkills.combat_xp)
}

// int32 athletics_lvl = 7;
inline void PBSkills::clear_athletics_lvl() {
  athletics_lvl_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::_internal_athletics_lvl() const {
  return athletics_lvl_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBSkills::athletics_lvl() const {
  // @@protoc_insertion_point(field_get:PBSkills.athletics_lvl)
  return _internal_athletics_lvl();
}
inline void PBSkills::_internal_set_athletics_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  athletics_lvl_ = value;
}
inline void PBSkills::set_athletics_lvl(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_athletics_lvl(value);
  // @@protoc_insertion_point(field_set:PBSkills.athletics_lvl)
}

// int64 athletics_xp = 8;
inline void PBSkills::clear_athletics_xp() {
  athletics_xp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::_internal_athletics_xp() const {
  return athletics_xp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PBSkills::athletics_xp() const {
  // @@protoc_insertion_point(field_get:PBSkills.athletics_xp)
  return _internal_athletics_xp();
}
inline void PBSkills::_internal_set_athletics_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  athletics_xp_ = value;
}
inline void PBSkills::set_athletics_xp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_athletics_xp(value);
  // @@protoc_insertion_point(field_set:PBSkills.athletics_xp)
}

// -------------------------------------------------------------------

// PBPlayer

// uint64 discord_id = 1;
inline void PBPlayer::clear_discord_id() {
  discord_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PBPlayer::_internal_discord_id() const {
  return discord_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PBPlayer::discord_id() const {
  // @@protoc_insertion_point(field_get:PBPlayer.discord_id)
  return _internal_discord_id();
}
inline void PBPlayer::_internal_set_discord_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  discord_id_ = value;
}
inline void PBPlayer::set_discord_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_discord_id(value);
  // @@protoc_insertion_point(field_set:PBPlayer.discord_id)
}

// int32 player_id = 2;
inline void PBPlayer::clear_player_id() {
  player_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBPlayer::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PBPlayer::player_id() const {
  // @@protoc_insertion_point(field_get:PBPlayer.player_id)
  return _internal_player_id();
}
inline void PBPlayer::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  player_id_ = value;
}
inline void PBPlayer::set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:PBPlayer.player_id)
}

// string user_name = 3;
inline void PBPlayer::clear_user_name() {
  user_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PBPlayer::user_name() const {
  // @@protoc_insertion_point(field_get:PBPlayer.user_name)
  return _internal_user_name();
}
inline void PBPlayer::set_user_name(const std::string& value) {
  _internal_set_user_name(value);
  // @@protoc_insertion_point(field_set:PBPlayer.user_name)
}
inline std::string* PBPlayer::mutable_user_name() {
  // @@protoc_insertion_point(field_mutable:PBPlayer.user_name)
  return _internal_mutable_user_name();
}
inline const std::string& PBPlayer::_internal_user_name() const {
  return user_name_.Get();
}
inline void PBPlayer::_internal_set_user_name(const std::string& value) {
  
  user_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PBPlayer::set_user_name(std::string&& value) {
  
  user_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PBPlayer.user_name)
}
inline void PBPlayer::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PBPlayer.user_name)
}
inline void PBPlayer::set_user_name(const char* value,
    size_t size) {
  
  user_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PBPlayer.user_name)
}
inline std::string* PBPlayer::_internal_mutable_user_name() {
  
  return user_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PBPlayer::release_user_name() {
  // @@protoc_insertion_point(field_release:PBPlayer.user_name)
  return user_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PBPlayer::set_allocated_user_name(std::string* user_name) {
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PBPlayer.user_name)
}
inline std::string* PBPlayer::unsafe_arena_release_user_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PBPlayer.user_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return user_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PBPlayer::unsafe_arena_set_allocated_user_name(
    std::string* user_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      user_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBPlayer.user_name)
}

// .google.protobuf.Timestamp last_online = 4;
inline bool PBPlayer::_internal_has_last_online() const {
  return this != internal_default_instance() && last_online_ != nullptr;
}
inline bool PBPlayer::has_last_online() const {
  return _internal_has_last_online();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PBPlayer::_internal_last_online() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = last_online_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PBPlayer::last_online() const {
  // @@protoc_insertion_point(field_get:PBPlayer.last_online)
  return _internal_last_online();
}
inline void PBPlayer::unsafe_arena_set_allocated_last_online(
    PROTOBUF_NAMESPACE_ID::Timestamp* last_online) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(last_online_);
  }
  last_online_ = last_online;
  if (last_online) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBPlayer.last_online)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PBPlayer::release_last_online() {
  auto temp = unsafe_arena_release_last_online();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PBPlayer::unsafe_arena_release_last_online() {
  // @@protoc_insertion_point(field_release:PBPlayer.last_online)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = last_online_;
  last_online_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PBPlayer::_internal_mutable_last_online() {
  
  if (last_online_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    last_online_ = p;
  }
  return last_online_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PBPlayer::mutable_last_online() {
  // @@protoc_insertion_point(field_mutable:PBPlayer.last_online)
  return _internal_mutable_last_online();
}
inline void PBPlayer::set_allocated_last_online(PROTOBUF_NAMESPACE_ID::Timestamp* last_online) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(last_online_);
  }
  if (last_online) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(last_online)->GetArena();
    if (message_arena != submessage_arena) {
      last_online = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, last_online, submessage_arena);
    }
    
  } else {
    
  }
  last_online_ = last_online;
  // @@protoc_insertion_point(field_set_allocated:PBPlayer.last_online)
}

// uint64 guild_id = 6;
inline void PBPlayer::clear_guild_id() {
  guild_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PBPlayer::_internal_guild_id() const {
  return guild_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PBPlayer::guild_id() const {
  // @@protoc_insertion_point(field_get:PBPlayer.guild_id)
  return _internal_guild_id();
}
inline void PBPlayer::_internal_set_guild_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  guild_id_ = value;
}
inline void PBPlayer::set_guild_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_guild_id(value);
  // @@protoc_insertion_point(field_set:PBPlayer.guild_id)
}

// .PBLocationID current_location = 7;
inline void PBPlayer::clear_current_location() {
  current_location_ = 0;
}
inline ::PBLocationID PBPlayer::_internal_current_location() const {
  return static_cast< ::PBLocationID >(current_location_);
}
inline ::PBLocationID PBPlayer::current_location() const {
  // @@protoc_insertion_point(field_get:PBPlayer.current_location)
  return _internal_current_location();
}
inline void PBPlayer::_internal_set_current_location(::PBLocationID value) {
  
  current_location_ = value;
}
inline void PBPlayer::set_current_location(::PBLocationID value) {
  _internal_set_current_location(value);
  // @@protoc_insertion_point(field_set:PBPlayer.current_location)
}

// .PBStats stats = 8;
inline bool PBPlayer::_internal_has_stats() const {
  return this != internal_default_instance() && stats_ != nullptr;
}
inline bool PBPlayer::has_stats() const {
  return _internal_has_stats();
}
inline void PBPlayer::clear_stats() {
  if (GetArena() == nullptr && stats_ != nullptr) {
    delete stats_;
  }
  stats_ = nullptr;
}
inline const ::PBStats& PBPlayer::_internal_stats() const {
  const ::PBStats* p = stats_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PBStats*>(
      &::_PBStats_default_instance_);
}
inline const ::PBStats& PBPlayer::stats() const {
  // @@protoc_insertion_point(field_get:PBPlayer.stats)
  return _internal_stats();
}
inline void PBPlayer::unsafe_arena_set_allocated_stats(
    ::PBStats* stats) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stats_);
  }
  stats_ = stats;
  if (stats) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBPlayer.stats)
}
inline ::PBStats* PBPlayer::release_stats() {
  auto temp = unsafe_arena_release_stats();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PBStats* PBPlayer::unsafe_arena_release_stats() {
  // @@protoc_insertion_point(field_release:PBPlayer.stats)
  
  ::PBStats* temp = stats_;
  stats_ = nullptr;
  return temp;
}
inline ::PBStats* PBPlayer::_internal_mutable_stats() {
  
  if (stats_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBStats>(GetArena());
    stats_ = p;
  }
  return stats_;
}
inline ::PBStats* PBPlayer::mutable_stats() {
  // @@protoc_insertion_point(field_mutable:PBPlayer.stats)
  return _internal_mutable_stats();
}
inline void PBPlayer::set_allocated_stats(::PBStats* stats) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete stats_;
  }
  if (stats) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(stats);
    if (message_arena != submessage_arena) {
      stats = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stats, submessage_arena);
    }
    
  } else {
    
  }
  stats_ = stats;
  // @@protoc_insertion_point(field_set_allocated:PBPlayer.stats)
}

// .PBSkills skills = 9;
inline bool PBPlayer::_internal_has_skills() const {
  return this != internal_default_instance() && skills_ != nullptr;
}
inline bool PBPlayer::has_skills() const {
  return _internal_has_skills();
}
inline void PBPlayer::clear_skills() {
  if (GetArena() == nullptr && skills_ != nullptr) {
    delete skills_;
  }
  skills_ = nullptr;
}
inline const ::PBSkills& PBPlayer::_internal_skills() const {
  const ::PBSkills* p = skills_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PBSkills*>(
      &::_PBSkills_default_instance_);
}
inline const ::PBSkills& PBPlayer::skills() const {
  // @@protoc_insertion_point(field_get:PBPlayer.skills)
  return _internal_skills();
}
inline void PBPlayer::unsafe_arena_set_allocated_skills(
    ::PBSkills* skills) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(skills_);
  }
  skills_ = skills;
  if (skills) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBPlayer.skills)
}
inline ::PBSkills* PBPlayer::release_skills() {
  auto temp = unsafe_arena_release_skills();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PBSkills* PBPlayer::unsafe_arena_release_skills() {
  // @@protoc_insertion_point(field_release:PBPlayer.skills)
  
  ::PBSkills* temp = skills_;
  skills_ = nullptr;
  return temp;
}
inline ::PBSkills* PBPlayer::_internal_mutable_skills() {
  
  if (skills_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBSkills>(GetArena());
    skills_ = p;
  }
  return skills_;
}
inline ::PBSkills* PBPlayer::mutable_skills() {
  // @@protoc_insertion_point(field_mutable:PBPlayer.skills)
  return _internal_mutable_skills();
}
inline void PBPlayer::set_allocated_skills(::PBSkills* skills) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete skills_;
  }
  if (skills) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(skills);
    if (message_arena != submessage_arena) {
      skills = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, skills, submessage_arena);
    }
    
  } else {
    
  }
  skills_ = skills;
  // @@protoc_insertion_point(field_set_allocated:PBPlayer.skills)
}

// .PBEquipation equipation = 10;
inline bool PBPlayer::_internal_has_equipation() const {
  return this != internal_default_instance() && equipation_ != nullptr;
}
inline bool PBPlayer::has_equipation() const {
  return _internal_has_equipation();
}
inline void PBPlayer::clear_equipation() {
  if (GetArena() == nullptr && equipation_ != nullptr) {
    delete equipation_;
  }
  equipation_ = nullptr;
}
inline const ::PBEquipation& PBPlayer::_internal_equipation() const {
  const ::PBEquipation* p = equipation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PBEquipation*>(
      &::_PBEquipation_default_instance_);
}
inline const ::PBEquipation& PBPlayer::equipation() const {
  // @@protoc_insertion_point(field_get:PBPlayer.equipation)
  return _internal_equipation();
}
inline void PBPlayer::unsafe_arena_set_allocated_equipation(
    ::PBEquipation* equipation) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(equipation_);
  }
  equipation_ = equipation;
  if (equipation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PBPlayer.equipation)
}
inline ::PBEquipation* PBPlayer::release_equipation() {
  auto temp = unsafe_arena_release_equipation();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PBEquipation* PBPlayer::unsafe_arena_release_equipation() {
  // @@protoc_insertion_point(field_release:PBPlayer.equipation)
  
  ::PBEquipation* temp = equipation_;
  equipation_ = nullptr;
  return temp;
}
inline ::PBEquipation* PBPlayer::_internal_mutable_equipation() {
  
  if (equipation_ == nullptr) {
    auto* p = CreateMaybeMessage<::PBEquipation>(GetArena());
    equipation_ = p;
  }
  return equipation_;
}
inline ::PBEquipation* PBPlayer::mutable_equipation() {
  // @@protoc_insertion_point(field_mutable:PBPlayer.equipation)
  return _internal_mutable_equipation();
}
inline void PBPlayer::set_allocated_equipation(::PBEquipation* equipation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete equipation_;
  }
  if (equipation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(equipation);
    if (message_arena != submessage_arena) {
      equipation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, equipation, submessage_arena);
    }
    
  } else {
    
  }
  equipation_ = equipation;
  // @@protoc_insertion_point(field_set_allocated:PBPlayer.equipation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PBPlayerStats> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PBPlayerStats>() {
  return ::PBPlayerStats_descriptor();
}
template <> struct is_proto_enum< ::PBPlayerSkills> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PBPlayerSkills>() {
  return ::PBPlayerSkills_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_player_2eproto
